import React from "react";
import { AutoComplete, TextField } from "material-ui";

var CountriesSelectField = React.createClass({
  propTypes: {
    model: React.PropTypes.object
  },

  contextTypes: {
    readOnly: React.PropTypes.bool
  },

  getValue() {
    return this.refs['menu'].getSelectedValue();
  },

  getDefaultProps() {
    return {
      codeStandard: 'alfa3'
    }
  },

  items() {
    return CountriesSelectField.countries.map((c)=> {
      return c.text;
    });
  },

  _setAttribute(v) {
    let country = CountriesSelectField.countries.find(c => {
      return c.text == v;
    });
    this.props.model.set(this.props.attribute,
                         country ? country[this.props.codeStandard] : v);
  },

  render() {
    let value = this.props.model.get(this.props.attribute);
    value = CountriesSelectField.countries.find(c =>
      c[this.props.codeStandard] == value
    );
    if(!value)
      value = {text: ''};

    if(this.context.readOnly)
      return <TextField value={value.text} readOnly={true} />;
    else
      return (
        <AutoComplete {...this.props}
                    dataSource={this.items()}
                    searchText={value.text}
                    onNewRequest={this._setAttribute}
                    floatingLabelText={this.props.label}
                    ref="menu"
                    className="country-select" />
    );
  },

  statics: {
    alfa2CountriesCodes() {
      return CountriesSelectField.countries.map((c)=> c.alfa2);
    },

    alfa3CountriesCodes() {
      return CountriesSelectField.countries.map((c)=> c.alfa3);
    },

    countries:  [ { text: 'Afganistan', alfa2: 'AF', alfa3: 'AFG' },
                  { text: 'Albania', alfa2: 'AL', alfa3: 'ALB' },
                  { text: 'Algeria', alfa2: 'DZ', alfa3: 'DZA' },
                  { text: 'American Samoa', alfa2: 'AS', alfa3: 'ASM' },
                  { text: 'Andorra', alfa2: 'AD', alfa3: 'AND' },
                  { text: 'Angola', alfa2: 'AO', alfa3: 'AGO' },
                  { text: 'Anguilla', alfa2: 'AI', alfa3: 'AIA' },
                  { text: 'Antarctica', alfa2: 'AQ', alfa3: 'ATA' },
                  { text: 'Antigua and Barbuda', alfa2: 'AG', alfa3: 'ATG' },
                  { text: 'Argentina', alfa2: 'AR', alfa3: 'ARG' },
                  { text: 'Armenia', alfa2: 'AM', alfa3: 'ARM' },
                  { text: 'Aruba', alfa2: 'AW', alfa3: 'ABW' },
                  { text: 'Australia', alfa2: 'AU', alfa3: 'AUS' },
                  { text: 'Austria', alfa2: 'AT', alfa3: 'AUT' },
                  { text: 'Azerbaijan', alfa2: 'AZ', alfa3: 'AZE' },
                  { text: 'Bahamas', alfa2: 'BS', alfa3: 'BHS' },
                  { text: 'Bahrain', alfa2: 'BH', alfa3: 'BHR' },
                  { text: 'Bangladesh', alfa2: 'BD', alfa3: 'BGD' },
                  { text: 'Barbados', alfa2: 'BB', alfa3: 'BRB' },
                  { text: 'Belarus', alfa2: 'BY', alfa3: 'BLR' },
                  { text: 'Belgium', alfa2: 'BE', alfa3: 'BEL' },
                  { text: 'Belize', alfa2: 'BZ', alfa3: 'BLZ' },
                  { text: 'Benin', alfa2: 'BJ', alfa3: 'BEN' },
                  { text: 'Bermuda', alfa2: 'BM', alfa3: 'BMU' },
                  { text: 'Bhutan', alfa2: 'BT', alfa3: 'BTN' },
                  { text: 'Bolivia, Plurinational State of',
                    alfa2: 'BO',
                    alfa3: 'BOL' },
                  { text: 'Bonaire, Sint Eustatius and Saba',
                    alfa2: 'BQ',
                    alfa3: 'BES' },
                  { text: 'Bosnia and Herzegovina', alfa2: 'BA', alfa3: 'BIH' },
                  { text: 'Botswana', alfa2: 'BW', alfa3: 'BWA' },
                  { text: 'Bouvet Island', alfa2: 'BV', alfa3: 'BVT' },
                  { text: 'Brazil', alfa2: 'BR', alfa3: 'BRA' },
                  { text: 'British Indian Ocean Territory',
                    alfa2: 'IO',
                    alfa3: 'IOT' },
                  { text: 'Brunei Darussalam', alfa2: 'BN', alfa3: 'BRN' },
                  { text: 'Bulgaria', alfa2: 'BG', alfa3: 'BGR' },
                  { text: 'Burkina Faso', alfa2: 'BF', alfa3: 'BFA' },
                  { text: 'Burundi', alfa2: 'BI', alfa3: 'BDI' },
                  { text: 'Cambodia', alfa2: 'KH', alfa3: 'KHM' },
                  { text: 'Cameroon', alfa2: 'CM', alfa3: 'CMR' },
                  { text: 'Canada', alfa2: 'CA', alfa3: 'CAN' },
                  { text: 'Cape Verde', alfa2: 'CV', alfa3: 'CPV' },
                  { text: 'Cayman Islands', alfa2: 'KY', alfa3: 'CYM' },
                  { text: 'Central African Republic', alfa2: 'CF', alfa3: 'CAF' },
                  { text: 'Chad', alfa2: 'TD', alfa3: 'TCD' },
                  { text: 'Chile', alfa2: 'CL', alfa3: 'CHL' },
                  { text: 'China', alfa2: 'CN', alfa3: 'CHN' },
                  { text: 'Christmas Island', alfa2: 'CX', alfa3: 'CXR' },
                  { text: 'Cocos (Keeling) Islands', alfa2: 'CC', alfa3: 'CCK' },
                  { text: 'Colombia', alfa2: 'CO', alfa3: 'COL' },
                  { text: 'Comoros', alfa2: 'KM', alfa3: 'COM' },
                  { text: 'Congo', alfa2: 'CG', alfa3: 'COG' },
                  { text: 'Congo, the Democratic Republic of the',
                    alfa2: 'CD',
                    alfa3: 'COD' },
                  { text: 'Cook Islands', alfa2: 'CK', alfa3: 'COK' },
                  { text: 'Costa Rica', alfa2: 'CR', alfa3: 'CRI' },
                  { text: 'Croatia', alfa2: 'HR', alfa3: 'HRV' },
                  { text: 'Cuba', alfa2: 'CU', alfa3: 'CUB' },
                  { text: 'Curaçao', alfa2: 'CW', alfa3: 'CUW' },
                  { text: 'Cyprus', alfa2: 'CY', alfa3: 'CYP' },
                  { text: 'Czech Republic', alfa2: 'CZ', alfa3: 'CZE' },
                  { text: 'Côte d\'Ivoire', alfa2: 'CI', alfa3: 'CIV' },
                  { text: 'Denmark', alfa2: 'DK', alfa3: 'DNK' },
                  { text: 'Djibouti', alfa2: 'DJ', alfa3: 'DJI' },
                  { text: 'Dominica', alfa2: 'DM', alfa3: 'DMA' },
                  { text: 'Dominican Republic', alfa2: 'DO', alfa3: 'DOM' },
                  { text: 'Ecuador', alfa2: 'EC', alfa3: 'ECU' },
                  { text: 'Egypt', alfa2: 'EG', alfa3: 'EGY' },
                  { text: 'El Salvador', alfa2: 'SV', alfa3: 'SLV' },
                  { text: 'Equatorial Guinea', alfa2: 'GQ', alfa3: 'GNQ' },
                  { text: 'Eritrea', alfa2: 'ER', alfa3: 'ERI' },
                  { text: 'Estonia', alfa2: 'EE', alfa3: 'EST' },
                  { text: 'Ethiopia', alfa2: 'ET', alfa3: 'ETH' },
                  { text: 'Falkland Islands (Malvinas)',
                    alfa2: 'FK',
                    alfa3: 'FLK' },
                  { text: 'Faroe Islands', alfa2: 'FO', alfa3: 'FRO' },
                  { text: 'Fiji', alfa2: 'FJ', alfa3: 'FJI' },
                  { text: 'Finland', alfa2: 'FI', alfa3: 'FIN' },
                  { text: 'France', alfa2: 'FR', alfa3: 'FRA' },
                  { text: 'French Guiana', alfa2: 'GF', alfa3: 'GUF' },
                  { text: 'French Polynesia', alfa2: 'PF', alfa3: 'PYF' },
                  { text: 'French Southern Territories',
                    alfa2: 'TF',
                    alfa3: 'ATF' },
                  { text: 'Gabon', alfa2: 'GA', alfa3: 'GAB' },
                  { text: 'Gambia', alfa2: 'GM', alfa3: 'GMB' },
                  { text: 'Georgia', alfa2: 'GE', alfa3: 'GEO' },
                  { text: 'Germany', alfa2: 'DE', alfa3: 'DEU' },
                  { text: 'Ghana', alfa2: 'GH', alfa3: 'GHA' },
                  { text: 'Gibraltar', alfa2: 'GI', alfa3: 'GIB' },
                  { text: 'Greece', alfa2: 'GR', alfa3: 'GRC' },
                  { text: 'Greenland', alfa2: 'GL', alfa3: 'GRL' },
                  { text: 'Grenada', alfa2: 'GD', alfa3: 'GRD' },
                  { text: 'Guadeloupe', alfa2: 'GP', alfa3: 'GLP' },
                  { text: 'Guam', alfa2: 'GU', alfa3: 'GUM' },
                  { text: 'Guatemala', alfa2: 'GT', alfa3: 'GTM' },
                  { text: 'Guernsey', alfa2: 'GG', alfa3: 'GGY' },
                  { text: 'Guinea', alfa2: 'GN', alfa3: 'GIN' },
                  { text: 'Guinea-Bissau', alfa2: 'GW', alfa3: 'GNB' },
                  { text: 'Guyana', alfa2: 'GY', alfa3: 'GUY' },
                  { text: 'Haiti', alfa2: 'HT', alfa3: 'HTI' },
                  { text: 'Heard Island and McDonald Islands',
                    alfa2: 'HM',
                    alfa3: 'HMD' },
                  { text: 'Holy See (Vatican City State)',
                    alfa2: 'VA',
                    alfa3: 'VAT' },
                  { text: 'Honduras', alfa2: 'HN', alfa3: 'HND' },
                  { text: 'Hong Kong', alfa2: 'HK', alfa3: 'HKG' },
                  { text: 'Hungary', alfa2: 'HU', alfa3: 'HUN' },
                  { text: 'Iceland', alfa2: 'IS', alfa3: 'ISL' },
                  { text: 'India', alfa2: 'IN', alfa3: 'IND' },
                  { text: 'Indonesia', alfa2: 'ID', alfa3: 'IDN' },
                  { text: 'Iran, Islamic Republic of', alfa2: 'IR', alfa3: 'IRN' },
                  { text: 'Iraq', alfa2: 'IQ', alfa3: 'IRQ' },
                  { text: 'Ireland', alfa2: 'IE', alfa3: 'IRL' },
                  { text: 'Isle of Man', alfa2: 'IM', alfa3: 'IMN' },
                  { text: 'Israel', alfa2: 'IL', alfa3: 'ISR' },
                  { text: 'Italy', alfa2: 'IT', alfa3: 'ITA' },
                  { text: 'Jamaica', alfa2: 'JM', alfa3: 'JAM' },
                  { text: 'Japan', alfa2: 'JP', alfa3: 'JPN' },
                  { text: 'Jersey', alfa2: 'JE', alfa3: 'JEY' },
                  { text: 'Jordan', alfa2: 'JO', alfa3: 'JOR' },
                  { text: 'Kazakhstan', alfa2: 'KZ', alfa3: 'KAZ' },
                  { text: 'Kenya', alfa2: 'KE', alfa3: 'KEN' },
                  { text: 'Kiribati', alfa2: 'KI', alfa3: 'KIR' },
                  { text: 'Korea, Democratic People\'s Republic of',
                    alfa2: 'KP',
                    alfa3: 'PRK' },
                  { text: 'Korea, Republic of', alfa2: 'KR', alfa3: 'KOR' },
                  { text: 'Kuwait', alfa2: 'KW', alfa3: 'KWT' },
                  { text: 'Kyrgyzstan', alfa2: 'KG', alfa3: 'KGZ' },
                  { text: 'Lao People\'s Democratic Republic',
                    alfa2: 'LA',
                    alfa3: 'LAO' },
                  { text: 'Latvia', alfa2: 'LV', alfa3: 'LVA' },
                  { text: 'Lebanon', alfa2: 'LB', alfa3: 'LBN' },
                  { text: 'Lesotho', alfa2: 'LS', alfa3: 'LSO' },
                  { text: 'Liberia', alfa2: 'LR', alfa3: 'LBR' },
                  { text: 'Libyan Arab Jamahiriya', alfa2: 'LY', alfa3: 'LBY' },
                  { text: 'Liechtenstein', alfa2: 'LI', alfa3: 'LIE' },
                  { text: 'Lithuania', alfa2: 'LT', alfa3: 'LTU' },
                  { text: 'Luxembourg', alfa2: 'LU', alfa3: 'LUX' },
                  { text: 'Macao', alfa2: 'MO', alfa3: 'MAC' },
                  { text: 'Macedonia, the former Yugoslav Republic of',
                    alfa2: 'MK',
                    alfa3: 'MKD' },
                  { text: 'Madagascar', alfa2: 'MG', alfa3: 'MDG' },
                  { text: 'Malawi', alfa2: 'MW', alfa3: 'MWI' },
                  { text: 'Malaysia', alfa2: 'MY', alfa3: 'MYS' },
                  { text: 'Maldives', alfa2: 'MV', alfa3: 'MDV' },
                  { text: 'Mali', alfa2: 'ML', alfa3: 'MLI' },
                  { text: 'Malta', alfa2: 'MT', alfa3: 'MLT' },
                  { text: 'Marshall Islands', alfa2: 'MH', alfa3: 'MHL' },
                  { text: 'Martinique', alfa2: 'MQ', alfa3: 'MTQ' },
                  { text: 'Mauritania', alfa2: 'MR', alfa3: 'MRT' },
                  { text: 'Mauritius', alfa2: 'MU', alfa3: 'MUS' },
                  { text: 'Mayotte', alfa2: 'YT', alfa3: 'MYT' },
                  { text: 'Mexico', alfa2: 'MX', alfa3: 'MEX' },
                  { text: 'Micronesia, Federated States of',
                    alfa2: 'FM',
                    alfa3: 'FSM' },
                  { text: 'Moldova, Republic of', alfa2: 'MD', alfa3: 'MDA' },
                  { text: 'Monaco', alfa2: 'MC', alfa3: 'MCO' },
                  { text: 'Mongolia', alfa2: 'MN', alfa3: 'MNG' },
                  { text: 'Montenegro', alfa2: 'ME', alfa3: 'MNE' },
                  { text: 'Montserrat', alfa2: 'MS', alfa3: 'MSR' },
                  { text: 'Morocco', alfa2: 'MA', alfa3: 'MAR' },
                  { text: 'Mozambique', alfa2: 'MZ', alfa3: 'MOZ' },
                  { text: 'Myanmar', alfa2: 'MM', alfa3: 'MMR' },
                  { text: 'Namibia', alfa2: 'NA', alfa3: 'NAM' },
                  { text: 'Nauru', alfa2: 'NR', alfa3: 'NRU' },
                  { text: 'Nepal', alfa2: 'NP', alfa3: 'NPL' },
                  { text: 'Netherlands', alfa2: 'NL', alfa3: 'NLD' },
                  { text: 'New Caledonia', alfa2: 'NC', alfa3: 'NCL' },
                  { text: 'New Zealand', alfa2: 'NZ', alfa3: 'NZL' },
                  { text: 'Nicaragua', alfa2: 'NI', alfa3: 'NIC' },
                  { text: 'Niger', alfa2: 'NE', alfa3: 'NER' },
                  { text: 'Nigeria', alfa2: 'NG', alfa3: 'NGA' },
                  { text: 'Niue', alfa2: 'NU', alfa3: 'NIU' },
                  { text: 'Norfolk Island', alfa2: 'NF', alfa3: 'NFK' },
                  { text: 'Northern Mariana Islands', alfa2: 'MP', alfa3: 'MNP' },
                  { text: 'Norway', alfa2: 'NO', alfa3: 'NOR' },
                  { text: 'Oman', alfa2: 'OM', alfa3: 'OMN' },
                  { text: 'Pakistan', alfa2: 'PK', alfa3: 'PAK' },
                  { text: 'Palau', alfa2: 'PW', alfa3: 'PLW' },
                  { text: 'Palestinian Territory, Occupied',
                    alfa2: 'PS',
                    alfa3: 'PSE' },
                  { text: 'Panama', alfa2: 'PA', alfa3: 'PAN' },
                  { text: 'Papua New Guinea', alfa2: 'PG', alfa3: 'PNG' },
                  { text: 'Paraguay', alfa2: 'PY', alfa3: 'PRY' },
                  { text: 'Peru', alfa2: 'PE', alfa3: 'PER' },
                  { text: 'Philippines', alfa2: 'PH', alfa3: 'PHL' },
                  { text: 'Pitcairn', alfa2: 'PN', alfa3: 'PCN' },
                  { text: 'Poland', alfa2: 'PL', alfa3: 'POL' },
                  { text: 'Portugal', alfa2: 'PT', alfa3: 'PRT' },
                  { text: 'Puerto Rico', alfa2: 'PR', alfa3: 'PRI' },
                  { text: 'Qatar', alfa2: 'QA', alfa3: 'QAT' },
                  { text: 'Romania', alfa2: 'RO', alfa3: 'ROU' },
                  { text: 'Russian Federation', alfa2: 'RU', alfa3: 'RUS' },
                  { text: 'Rwanda', alfa2: 'RW', alfa3: 'RWA' },
                  { text: 'Réunion', alfa2: 'RE', alfa3: 'REU' },
                  { text: 'Saint Barthélemy', alfa2: 'BL', alfa3: 'BLM' },
                  { text: 'Saint Helena, Ascension and Tristan da Cunha',
                    alfa2: 'SH',
                    alfa3: 'SHN' },
                  { text: 'Saint Kitts and Nevis', alfa2: 'KN', alfa3: 'KNA' },
                  { text: 'Saint Lucia', alfa2: 'LC', alfa3: 'LCA' },
                  { text: 'Saint Martin (French part)', alfa2: 'MF', alfa3: 'MAF' },
                  { text: 'Saint Pierre and Miquelon', alfa2: 'PM', alfa3: 'SPM' },
                  { text: 'Saint Vincent and the Grenadines',
                    alfa2: 'VC',
                    alfa3: 'VCT' },
                  { text: 'Samoa', alfa2: 'WS', alfa3: 'WSM' },
                  { text: 'San Marino', alfa2: 'SM', alfa3: 'SMR' },
                  { text: 'Sao Tome and Principe', alfa2: 'ST', alfa3: 'STP' },
                  { text: 'Saudi Arabia', alfa2: 'SA', alfa3: 'SAU' },
                  { text: 'Senegal', alfa2: 'SN', alfa3: 'SEN' },
                  { text: 'Serbia', alfa2: 'RS', alfa3: 'SRB' },
                  { text: 'Seychelles', alfa2: 'SC', alfa3: 'SYC' },
                  { text: 'Sierra Leone', alfa2: 'SL', alfa3: 'SLE' },
                  { text: 'Singapore', alfa2: 'SG', alfa3: 'SGP' },
                  { text: 'Sint Maarten (Dutch part)', alfa2: 'SX', alfa3: 'SXM' },
                  { text: 'Slovakia', alfa2: 'SK', alfa3: 'SVK' },
                  { text: 'Slovenia', alfa2: 'SI', alfa3: 'SVN' },
                  { text: 'Solomon Islands', alfa2: 'SB', alfa3: 'SLB' },
                  { text: 'Somalia', alfa2: 'SO', alfa3: 'SOM' },
                  { text: 'South Africa', alfa2: 'ZA', alfa3: 'ZAF' },
                  { text: 'South Georgia and the South Sandwich Islands',
                    alfa2: 'GS',
                    alfa3: 'SGS' },
                  { text: 'South Sudan', alfa2: 'SS', alfa3: 'SSD' },
                  { text: 'Spain', alfa2: 'ES', alfa3: 'ESP' },
                  { text: 'Sri Lanka', alfa2: 'LK', alfa3: 'LKA' },
                  { text: 'Sudan', alfa2: 'SD', alfa3: 'SDN' },
                  { text: 'Suriname', alfa2: 'SR', alfa3: 'SUR' },
                  { text: 'Svalbard and Jan Mayen', alfa2: 'SJ', alfa3: 'SJM' },
                  { text: 'Swaziland', alfa2: 'SZ', alfa3: 'SWZ' },
                  { text: 'Sweden', alfa2: 'SE', alfa3: 'SWE' },
                  { text: 'Switzerland', alfa2: 'CH', alfa3: 'CHE' },
                  { text: 'Syrian Arab Republic', alfa2: 'SY', alfa3: 'SYR' },
                  { text: 'Taiwan, Province of China', alfa2: 'TW', alfa3: 'TWN' },
                  { text: 'Tajikistan', alfa2: 'TJ', alfa3: 'TJK' },
                  { text: 'Tanzania, United Republic of',
                    alfa2: 'TZ',
                    alfa3: 'TZA' },
                  { text: 'Thailand', alfa2: 'TH', alfa3: 'THA' },
                  { text: 'Timor-Leste', alfa2: 'TL', alfa3: 'TLS' },
                  { text: 'Togo', alfa2: 'TG', alfa3: 'TGO' },
                  { text: 'Tokelau', alfa2: 'TK', alfa3: 'TKL' },
                  { text: 'Tonga', alfa2: 'TO', alfa3: 'TON' },
                  { text: 'Trinidad and Tobago', alfa2: 'TT', alfa3: 'TTO' },
                  { text: 'Tunisia', alfa2: 'TN', alfa3: 'TUN' },
                  { text: 'Turkey', alfa2: 'TR', alfa3: 'TUR' },
                  { text: 'Turkmenistan', alfa2: 'TM', alfa3: 'TKM' },
                  { text: 'Turks and Caicos Islands', alfa2: 'TC', alfa3: 'TCA' },
                  { text: 'Tuvalu', alfa2: 'TV', alfa3: 'TUV' },
                  { text: 'Uganda', alfa2: 'UG', alfa3: 'UGA' },
                  { text: 'Ukraine', alfa2: 'UA', alfa3: 'UKR' },
                  { text: 'United Arab Emirates', alfa2: 'AE', alfa3: 'ARE' },
                  { text: 'United Kingdom', alfa2: 'GB', alfa3: 'GBR' },
                  { text: 'United States', alfa2: 'US', alfa3: 'USA' },
                  { text: 'United States Minor Outlying Islands',
                    alfa2: 'UM',
                    alfa3: 'UMI' },
                  { text: 'Uruguay', alfa2: 'UY', alfa3: 'URY' },
                  { text: 'Uzbekistan', alfa2: 'UZ', alfa3: 'UZB' },
                  { text: 'Vanuatu', alfa2: 'VU', alfa3: 'VUT' },
                  { text: 'Venezuela, Bolivarian Republic of',
                    alfa2: 'VE',
                    alfa3: 'VEN' },
                  { text: 'Viet Nam', alfa2: 'VN', alfa3: 'VNM' },
                  { text: 'Virgin Islands, British', alfa2: 'VG', alfa3: 'VGB' },
                  { text: 'Virgin Islands, U.S.', alfa2: 'VI', alfa3: 'VIR' },
                  { text: 'Wallis and Futuna', alfa2: 'WF', alfa3: 'WLF' },
                  { text: 'Western Sahara', alfa2: 'EH', alfa3: 'ESH' },
                  { text: 'Yemen', alfa2: 'YE', alfa3: 'YEM' },
                  { text: 'Zambia', alfa2: 'ZM', alfa3: 'ZMB' },
                  { text: 'Zimbabwe', alfa2: 'ZW', alfa3: 'ZWE' },
                  { text: 'Åland Islands', alfa2: 'AX', alfa3: 'ALA' } ]
}
});

module.exports = CountriesSelectField;
